### ISSUE TITLE
Como funciona?

### ISSUE THREAD

**Issue by Bruno-Furtado** [canassa/sodexo-api#1]
Opa,

Cara, essa API funciona?
Se funcionar é sensacional haha.

É possível passar os comandos para utiliza-la?

Valeuu.
Abraço!

**Comment by Bruno-Furtado** [comment]
Acredito que seja necessário instalar essas dependências do Python, correto?

**Comment by canassa** [comment]
Infelizmente não funciona :(

O problema foi que eu não consegui vencer o captcha do site deles de uma maneira decente. No arquivo `captcha.py` tem as minhas tentativas de resolver o problema. Eu obtive um certo progresso  mas no final acabei desanimando de desistindo do projeto.

Abraços!

**Comment by Bruno-Furtado** [comment]
Eu notei que na request do POST eles enviam o CPF, número do cartão, captcha, x e y.

Sabe qual o motivo de existir o X e Y?
São apenas essas as regras para obter os dados?
Não existe nada armazenado em cookie?

Vou tentar utilizar a sua lógica e criar uma API em Java.

**Comment by canassa** [comment]
O X e Y não servem para nada, não faço idéia de porque eles colocaram isso no POST. Você pode envia sempre 6 e 9 que funciona haha.

Tem um cookie sim, a autenticação retorna um JSESSIONID que você precisa enviar para acessar as areas autenticadas.

Se você quiser testar, o código que está no `saldo.py` deve fazer a autenticação e extrair o saldo. Ele só não resolve o captcha.

**Comment by Bruno-Furtado** [comment]
Valeu @canassa!

Vou tentar aqui...
Abraço!
